openapi: 3.0.0
info:
  title: InsightHub API
  description: API para verificación y análisis de perfiles de redes sociales
  version: 1.0.0
servers:
  - url: /
    description: Servidor local
tags:
  - name: Salud
    description: Endpoints de monitoreo y salud
  - name: Social
    description: Verificación de redes sociales
  - name: Analytics
    description: Análisis y métricas
paths:
  /health:
    get:
      tags:
        - Salud
      summary: Verificar estado del sistema
      description: Retorna el estado de salud del sistema y sus componentes
      responses:
        '200':
          description: Sistema saludable
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: healthy
                  version:
                    type: string
                    example: 1.0.0
                  timestamp:
                    type: string
                    format: date-time
                  checks:
                    type: object
                    properties:
                      database:
                        type: boolean
                      redis:
                        type: boolean
                      external_apis:
                        type: boolean
  /check_social:
    get:
      tags:
        - Social
      summary: Página de verificación social
      description: Muestra el formulario para verificar perfiles sociales
      responses:
        '200':
          description: Página HTML con el formulario
    post:
      tags:
        - Social
      summary: Verificar perfiles sociales
      description: Analiza los perfiles de redes sociales proporcionados
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                instagram_url:
                  type: string
                  example: https://instagram.com/usuario
                twitter_url:
                  type: string
                  example: https://twitter.com/usuario
                linkedin_url:
                  type: string
                  example: https://linkedin.com/in/usuario
                facebook_url:
                  type: string
                  example: https://facebook.com/usuario
                tiktok_url:
                  type: string
                  example: https://tiktok.com/@usuario
      responses:
        '200':
          description: Resultados del análisis
        '400':
          description: Error en los datos proporcionados
  /analytics:
    get:
      tags:
        - Analytics
      summary: Dashboard de analytics
      description: Muestra estadísticas y métricas de uso
      responses:
        '200':
          description: Página de analytics
  /metrics:
    get:
      tags:
        - Salud
      summary: Métricas Prometheus
      description: Endpoint para métricas de Prometheus
      responses:
        '200':
          description: Métricas en formato Prometheus
components:
  schemas:
    HealthCheck:
      type: object
      properties:
        status:
          type: string
        version:
          type: string
        timestamp:
          type: string
          format: date-time
        checks:
          type: object
          properties:
            database:
              type: boolean
            redis:
              type: boolean
            external_apis:
              type: boolean
    Error:
      type: object
      properties:
        error:
          type: string
        status:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
